# NOTE: update this with your service name
service: spin-common

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}

  # webpack:
  #   webpackConfig: ./webpack.config.js
  #   includeModules:
  #     forceExclude:
  #       - ''
  #   packager: 'yarn'

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-2

layers:
  libs:
    path: src
  nodejs:
    path: dist

resources:
  Outputs:
    Libs:
      Value:
        Ref: LibsLambdaLayer
      Export:
        Name: LibsLambdaLayer
    Nodejs:
      Value:
        Ref: NodejsLambdaLayer
      Export:
        Name: NodejsLambdaLayer
